### ISSUE TITLE
general suggestion for component file structure

### ISSUE THREAD

**Issue by BioPhoton** [lamisChebbi/ng-realtime-dashboard#2]
As this is a tutorial I suggest moving everything related to one component (ts, html, css) into one file. 
This helps the reader to have everything in one place and they will spend less time understanding it.

**Comment by lamisChebbi** [comment]
This was taken into account in the last commit https://github.com/lamisChebbi/ng-realtime-dashboard/commit/8f4fbc21fc1b33bc089a04d180e72f6a6f4f7ccf
